spring.application.name=talenthub-recruitment

spring.datasource.url=jdbc:postgresql://ep-holy-base-atsv98lw.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0HLRkwT2CQEN
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.sql.init.mode=never

# ── Gmail SMTP ─────────────────────────────────────────────
# Điền Gmail và App Password (Cài đặt Google → Bảo mật → 2FA → Mật khẩu ứng dụng)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tungtrandang2006@gmail.com
spring.mail.password=xctfpbwtichymbff
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
