package com.talenthub.recruitment.entity.enums;

public enum AuditEventType {
    SIGN_IN_SUCCESS,
    SIGN_IN_FAILURE,
    ACCOUNT_CREATED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_LOCKED,
    APPLICATION_STATUS_CHANGED,
    CV_DOWNLOADED,
    EVALUATION_SUBMITTED
}
